#!/usr/bin/env node
// Usage: node scripts/build.js [--check]
// Generates each mod's vote/{ideas,version}.json and seed/seed.sql from data/catalogue.json
// (Ghostty's) and data/catalogues/*.json (every other mod's), src/almanac-schema.js from the published results schema, and
// public/mods/ffxiv/plugins.json + src/mods-data.js from data/mods.json. --check writes nothing and fails if any output is stale.
// No dependencies; wrangler runs this as the [build] command before deploy.
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildSeedSqlAll } from './seed-lib.js';
import { buildOutputs } from './static-lib.js';
import { STATIC_PLUGINS, buildPluginMaster } from './plugins-lib.js';
import { buildVotePages } from './vote-page-lib.js';

const root = fileURLToPath(new URL('..', import.meta.url));
const catalogue = JSON.parse(readFileSync(root + 'data/catalogue.json', 'utf8'));
// Ghostty's catalogue first, then every other mod's, in name order so the seed is stable.
const others = readdirSync(root + 'data/catalogues').filter((f) => f.endsWith('.json')).sort()
  .map((f) => JSON.parse(readFileSync(root + 'data/catalogues/' + f, 'utf8')));
const outputs = buildOutputs([catalogue, ...others], buildSeedSqlAll);
// Every mod's vote page, from one template and data/vote-pages.json.
Object.assign(outputs, buildVotePages(JSON.parse(readFileSync(root + 'data/vote-pages.json', 'utf8'))));
// The Almanac leaderboard's submission schema: the Worker validates against the same file
// the site publishes at /mods/ffxiv/almanac/schema/results.v1.json.
const resultsSchema = JSON.parse(readFileSync(root + 'public/mods/ffxiv/almanac/schema/results.v1.json', 'utf8'));
outputs['src/almanac-schema.js'] = '// Generated by scripts/build.js from public/mods/ffxiv/almanac/schema/results.v1.json; do not edit.\n' +
  'export default ' + JSON.stringify(resultsSchema, null, 2) + ';\n';
// The Dalamud plugin repository: the committed listing the Worker falls back to when
// GitHub cannot be reached, and the same data as a module the Worker can import.
const mods = JSON.parse(readFileSync(root + 'data/mods.json', 'utf8'));
outputs[STATIC_PLUGINS] = buildPluginMaster(mods);
outputs['src/mods-data.js'] = '// Generated by scripts/build.js from data/mods.json; do not edit.\n' +
  'export default ' + JSON.stringify(mods, null, 2) + ';\n';
const check = process.argv.includes('--check');
let stale = 0;

for (const [path, body] of Object.entries(outputs)) {
  let current = null;
  try { current = readFileSync(root + path, 'utf8'); } catch {}
  if (current === body) continue;
  if (check) {
    console.error(`${path} is out of date; run: node scripts/build.js`);
    stale++;
  } else {
    mkdirSync(dirname(root + path), { recursive: true });
    writeFileSync(root + path, body);
    console.log(`wrote ${path}`);
  }
}
if (stale) process.exit(1);
console.log(`${1 + others.length} vote catalogues (ghostty v${catalogue.version}): ${check ? "outputs are current" : "build done"}`);
