// Turns data/catalogue.json (Ghostty's) and data/catalogues/*.json (every other mod's)
// into idempotent D1 seed SQL. Pure; no I/O.

import { VOTE_MODS } from '../src/lib.js';

export const ID_RE = /^[a-z0-9][a-z0-9-]{0,63}$/;

// SQLite string literal. Doubling quotes is the only escape SQLite needs;
// NUL is rejected because D1/SQLite text would silently truncate on it.
export function sqlString(value) {
  const s = String(value);
  if (s.includes('\u0000')) throw new Error('NUL byte in SQL string');
  return "'" + s.replaceAll("'", "''") + "'";
}

function sqlInt(n, name) {
  if (!Number.isSafeInteger(n)) throw new Error(`${name} must be an integer`);
  return String(n);
}

const str = (v) => typeof v === 'string';

export function validateCatalogue(cat) {
  const errors = [];
  if (!cat || typeof cat !== 'object') return ['catalogue must be an object'];
  if (cat.mod !== undefined && !Object.hasOwn(VOTE_MODS, cat.mod)) errors.push(`mod "${cat.mod}" has no vote page (src/lib.js VOTE_MODS)`);
  if (!Number.isSafeInteger(cat.version) || cat.version < 1) errors.push('version must be an integer >= 1');
  if (!Array.isArray(cat.categories) || !cat.categories.length) errors.push('categories must be a non-empty array');
  const ids = new Set();
  const names = new Set();
  for (const [ci, c] of (cat.categories || []).entries()) {
    const where = `categories[${ci}]`;
    if (!str(c.name) || !c.name.trim()) errors.push(`${where}.name is required`);
    else if (names.has(c.name)) errors.push(`${where}.name duplicates "${c.name}"`);
    names.add(c.name);
    if (c.tagline !== undefined && !str(c.tagline)) errors.push(`${where}.tagline must be a string`);
    if (!Array.isArray(c.ideas)) { errors.push(`${where}.ideas must be an array`); continue; }
    for (const [ii, i] of c.ideas.entries()) {
      const w = `${where}.ideas[${ii}]`;
      if (!str(i.id) || !ID_RE.test(i.id)) errors.push(`${w}.id must match ${ID_RE}`);
      else if (ids.has(i.id)) errors.push(`${w}.id duplicates "${i.id}"`);
      ids.add(i.id);
      if (!str(i.title) || !i.title.trim()) errors.push(`${w}.title is required`);
      for (const k of ['pitch', 'experience', 'how', 'risks', 'audience', 'feasibility', 'effort']) {
        if (i[k] !== undefined && !str(i[k])) errors.push(`${w}.${k} must be a string`);
      }
      for (const k of ['in_world', 'tos_safe']) {
        if (i[k] !== undefined && typeof i[k] !== 'boolean') errors.push(`${w}.${k} must be a boolean`);
      }
      if (!Number.isSafeInteger(i.wow) || i.wow < 0 || i.wow > 10) errors.push(`${w}.wow must be an integer 0..10`);
      if (!Number.isSafeInteger(i.added_version) || i.added_version < 1 || i.added_version > cat.version) {
        errors.push(`${w}.added_version must be an integer 1..version (${cat.version})`);
      }
    }
  }
  for (const id of cat.top_picks || []) if (!ids.has(id)) errors.push(`top_picks references unknown id "${id}"`);
  return errors;
}

// A catalogue with no `mod` is Ghostty's (data/catalogue.json, the original vote).
export const catalogueMod = (cat) => cat.mod || 'ghostty';

// Every mod's catalogue must keep its idea ids and category names apart from the others',
// because votes, tallies and categories are keyed by them alone.
export function validateCatalogues(cats) {
  const errors = [];
  const mods = new Set();
  const ids = new Map();
  const names = new Map();
  for (const cat of cats) {
    const mod = catalogueMod(cat);
    for (const e of validateCatalogue(cat)) errors.push(`${mod}: ${e}`);
    if (mods.has(mod)) errors.push(`${mod}: a second catalogue for the same mod`);
    mods.add(mod);
    for (const c of cat.categories || []) {
      if (names.has(c.name) && names.get(c.name) !== mod) errors.push(`${mod}: category "${c.name}" is also ${names.get(c.name)}'s`);
      names.set(c.name, mod);
      for (const i of c.ideas || []) {
        if (ids.has(i.id) && ids.get(i.id) !== mod) errors.push(`${mod}: idea id "${i.id}" is also ${ids.get(i.id)}'s`);
        ids.set(i.id, mod);
      }
    }
  }
  return errors;
}

// One seed for every catalogue: Ghostty's first (it owns the single catalogue row the
// plugin's version check reads), then each other mod's.
export function buildSeedSqlAll(cats) {
  const errors = validateCatalogues(cats);
  if (errors.length) throw new Error('invalid catalogues:\n  ' + errors.join('\n  '));
  return cats.map((c) => buildSeedSql(c)).join('\n');
}

export function buildSeedSql(cat) {
  const errors = validateCatalogue(cat);
  if (errors.length) throw new Error('invalid catalogue:\n  ' + errors.join('\n  '));
  const mod = catalogueMod(cat);
  const ghostty = mod === 'ghostty';
  const top = new Set(cat.top_picks || []);
  const ideas = cat.categories.flatMap((c) => c.ideas.map((i) => ({ ...i, category: c.name })));
  const out = ghostty ? [
    '-- Generated by scripts/build.js from data/catalogue.json. Do not edit by hand.',
    `-- Catalogue version ${cat.version}: ${cat.categories.length} categories, ${ideas.length} ideas.`,
    '-- Idempotent: safe to re-run. Votes and tallies are never touched.',
    '',
    `INSERT INTO catalogue (id, version) VALUES (1, ${sqlInt(cat.version, 'version')})`,
    '  ON CONFLICT (id) DO UPDATE SET version = excluded.version',
    '  WHERE excluded.version >= catalogue.version;',
    '',
  ] : [
    `-- ${mod}: generated by scripts/build.js from data/catalogues/${mod}.json. Do not edit by hand.`,
    `-- Catalogue version ${cat.version}: ${cat.categories.length} categories, ${ideas.length} ideas.`,
    '',
  ];
  cat.categories.forEach((c, n) => {
    out.push(
      `INSERT INTO categories (name, tagline, sort_order, mod) VALUES (${sqlString(c.name)}, ${sqlString(c.tagline || '')}, ${n}, ${sqlString(mod)})` +
        ' ON CONFLICT (name) DO UPDATE SET tagline = excluded.tagline, sort_order = excluded.sort_order, mod = excluded.mod;',
    );
  });
  out.push('');
  const cols = ['id', 'mod', 'category', 'title', 'pitch', 'experience', 'how', 'risks', 'audience', 'in_world', 'tos_safe',
    'top_pick', 'wow', 'feasibility', 'effort', 'sort_order', 'added_version', 'retired'];
  const updates = cols.filter((k) => k !== 'id').map((k) => `${k} = excluded.${k}`).join(', ');
  ideas.forEach((i, n) => {
    const vals = [
      sqlString(i.id), sqlString(mod), sqlString(i.category), sqlString(i.title), sqlString(i.pitch || ''),
      sqlString(i.experience || ''), sqlString(i.how || ''), sqlString(i.risks || ''), sqlString(i.audience || ''),
      i.in_world ? 1 : 0, i.tos_safe === false ? 0 : 1, top.has(i.id) ? 1 : 0, sqlInt(i.wow, 'wow'),
      sqlString(i.feasibility || ''), sqlString(i.effort || ''), n, sqlInt(i.added_version, 'added_version'), 0,
    ];
    out.push(`INSERT INTO ideas (${cols.join(', ')}) VALUES (${vals.join(', ')})`);
    out.push(`  ON CONFLICT (id) DO UPDATE SET ${updates};`);
  });
  out.push('');
  out.push('-- Ideas removed from the catalogue are hidden, not deleted, so their votes survive.');
  out.push(`UPDATE ideas SET retired = 1 WHERE mod = ${sqlString(mod)} AND id NOT IN (${ideas.map((i) => sqlString(i.id)).join(', ')});`);
  out.push('');
  return out.join('\n');
}
