// Generated by scripts/build.js from data/mods.json; do not edit.
export default {
  "version": 1,
  "_comment": [
    "Every FFXIV mod published here, and the ones that are not published yet.",
    "scripts/build.js turns this into public/mods/ffxiv/plugins.json, the Dalamud plugin",
    "repository listing players add in /xlsettings. That file is only the fallback: the",
    "Worker (src/plugins.js) serves the same URL from each repository's own release",
    "assets so a release updates the listing without a deploy here, and falls back to the",
    "committed file when GitHub cannot be reached.",
    "listed=false keeps a mod off the listing but on the page: that is where a mod waits",
    "until its repository is public. released=true says that repository has published a",
    "release, so the fallback listing may name its download; the served listing does not",
    "need it, because it only carries what GitHub actually answers for."
  ],
  "mods": [
    {
      "internalName": "GhosttyDalamud",
      "name": "Ghostty",
      "listed": true,
      "released": false,
      "repo": "Spaceghost/ghostty-dalamud",
      "assemblyVersion": "0.2.0.0",
      "dalamudApiLevel": 15,
      "author": "Johnneylee Jack Rollins",
      "punchline": "Eorzea is a terminal multiplexer.",
      "description": "Quake-style dropdown, floating windows and terminals pinned in the world, connected to shells on your own machine through ghostty-agent. /term to toggle. Works with or without Umbra; with Umbra, the Ghostty toolbar widget shows its status and a popup terminal.",
      "tags": [
        "terminal",
        "ghostty",
        "utility"
      ],
      "icon": "https://spacegho.st/mods/ffxiv/plugins/icons/ghostty.png",
      "images": [
        "https://spacegho.st/mods/ffxiv/plugins/icons/ghostty-banner.png"
      ],
      "needs": "ghostty-agent running on the machine the game runs on.",
      "build": "tools/build.sh, then tools/package.sh",
      "umbraWidget": "Umbra.Ghostty"
    },
    {
      "internalName": "Almanac",
      "name": "Almanac",
      "listed": true,
      "released": true,
      "repo": "Spaceghost/almanac-dalamud",
      "assemblyVersion": "0.1.0.0",
      "dalamudApiLevel": 15,
      "author": "Johnneylee Jack Rollins",
      "punchline": "Talk to a local AI model in game, with XivMcp's tools.",
      "description": "Connects a model running on your own PC (Ollama, LM Studio, llama.cpp or any OpenAI-compatible server) to the game through XivMcp. Setup wizard with GPU-aware model recommendations, an in-game chat with threads and streaming, and a benchmark you can share with the community leaderboard. No cloud, no Python. Requires the XivMcp plugin for game tools.",
      "tags": [
        "ai",
        "llm",
        "local",
        "mcp",
        "chat",
        "utility"
      ],
      "icon": "https://raw.githubusercontent.com/Spaceghost/almanac-dalamud/master/images/icon.png",
      "images": [
        "https://raw.githubusercontent.com/Spaceghost/almanac-dalamud/master/images/banner.png"
      ],
      "needs": "A local model server (Ollama, LM Studio, llama.cpp or any OpenAI-compatible API), and XivMcp for game tools.",
      "build": "dotnet build dalamud/Almanac.Dalamud.slnx -c Release",
      "umbraWidget": null
    },
    {
      "internalName": "XivMcp",
      "name": "XivMcp",
      "listed": true,
      "repo": "Spaceghost/xiv-mcp",
      "assemblyVersion": "0.1.0.0",
      "dalamudApiLevel": 15,
      "author": "Johnneylee Jack Rollins",
      "punchline": "Model Context Protocol server for FINAL FANTASY XIV.",
      "description": "Exposes game state, game data and opt-in actions to MCP clients over loopback Streamable HTTP. Anything that changes your game is approved in game first. Optional Umbra toolbar widget.",
      "tags": [
        "mcp",
        "ai",
        "api",
        "utility"
      ],
      "icon": "https://spacegho.st/mods/ffxiv/plugins/icons/xivmcp.png",
      "images": [
        "https://spacegho.st/mods/ffxiv/plugins/icons/xivmcp-banner.png"
      ],
      "needs": "An MCP client on the same machine (Claude Code, Codex, Almanac).",
      "build": "dotnet build XivMcp.slnx -c Release",
      "umbraWidget": "Umbra.XivMcp",
      "pending": "The repository is not public yet, so there is nothing for the installer to download. Build it yourself in the meantime."
    },
    {
      "internalName": "XivDesktop",
      "name": "XivDesktop",
      "listed": true,
      "repo": "Spaceghost/xiv-desktop",
      "assemblyVersion": "1.0.0.0",
      "dalamudApiLevel": 15,
      "author": "Johnneylee Jack Rollins",
      "punchline": "Launch Linux desktop apps into the game world.",
      "description": "An app launcher for FINAL FANTASY XIV running under Wine on Linux. Lists the host's freedesktop applications and opens them as world panels through Ghostty's remote windows. Optional Umbra toolbar widget.",
      "tags": [
        "launcher",
        "desktop",
        "linux",
        "utility"
      ],
      "icon": "https://spacegho.st/mods/ffxiv/plugins/icons/xivdesktop.png",
      "images": [
        "https://spacegho.st/mods/ffxiv/plugins/icons/xivdesktop-banner.png"
      ],
      "needs": "Ghostty and ghostty-agent, and a Linux host running the game under Wine.",
      "build": "dotnet build XivDesktop.slnx -c Release",
      "umbraWidget": null,
      "pending": "The repository is not public yet, so there is nothing for the installer to download. Build it yourself in the meantime."
    }
  ]
};
