// Generated by scripts/build.js from data/mods.json; do not edit.
export default {
  "version": 1,
  "_comment": [
    "Every FFXIV mod published here, and the ones that are not published yet.",
    "scripts/build.js turns this into public/mods/ffxiv/plugins.json, the Dalamud plugin",
    "repository listing players add in /xlsettings. That file is only the fallback: the",
    "Worker (src/plugins.js) serves the same URL from each repository's own release",
    "assets so a release updates the listing without a deploy here, and falls back to the",
    "committed file when GitHub cannot be reached.",
    "listed=false keeps a mod off the listing but on the page: that is where a mod waits",
    "until its repository is public. released=true says that repository has published a",
    "release, so the fallback listing may name its download; the served listing does not",
    "need it, because it only carries what GitHub actually answers for."
  ],
  "mods": [
    {
      "internalName": "GhosttyDalamud",
      "name": "Ghostty",
      "listed": true,
      "released": true,
      "repo": "Spaceghost/ghostty-dalamud",
      "assemblyVersion": "0.3.0.2",
      "dalamudApiLevel": 15,
      "author": "Johnneylee Jack Rollins",
      "punchline": "Eorzea is a terminal multiplexer.",
      "description": "Quake-style dropdown, floating windows and terminals pinned in the world, connected to shells on your own machine through ghostty-agent. /term to toggle. Works with or without Umbra; with Umbra, the Ghostty toolbar widget shows its status and a popup terminal.",
      "tags": [
        "terminal",
        "ghostty",
        "utility"
      ],
      "icon": "https://spacegho.st/mods/ffxiv/plugins/icons/ghostty.png",
      "images": [
        "https://spacegho.st/mods/ffxiv/plugins/icons/ghostty-banner.png"
      ],
      "needs": "ghostty-agent running on the machine the game runs on.",
      "build": "tools/build.sh, then tools/package.sh",
      "umbraWidget": "Umbra.Ghostty"
    },
    {
      "internalName": "Almanac",
      "name": "Almanac",
      "listed": true,
      "released": true,
      "repo": "Spaceghost/almanac-dalamud",
      "assemblyVersion": "0.2.1.5",
      "dalamudApiLevel": 15,
      "author": "Johnneylee Jack Rollins",
      "punchline": "Talk to a local AI model in game, with XivMcp's tools.",
      "description": "Connects a model running on your own PC (Ollama, LM Studio, llama.cpp or any OpenAI-compatible server) to the game through XivMcp. Setup wizard with GPU-aware model recommendations, an in-game chat with threads and streaming, and a benchmark you can share with the community leaderboard. No cloud, no Python. Requires the XivMcp plugin for game tools.",
      "tags": [
        "ai",
        "llm",
        "local",
        "mcp",
        "chat",
        "utility"
      ],
      "icon": "https://spacegho.st/mods/ffxiv/plugins/icons/almanac.png",
      "images": [
        "https://spacegho.st/mods/ffxiv/plugins/icons/almanac-banner.png"
      ],
      "needs": "A local model server (Ollama, LM Studio, llama.cpp or any OpenAI-compatible API), and XivMcp for game tools.",
      "build": "dotnet build dalamud/Almanac.Dalamud.slnx -c Release",
      "umbraWidget": null
    },
    {
      "internalName": "XivMcp",
      "name": "XivMcp",
      "listed": true,
      "repo": "Spaceghost/xivmcp-dalamud",
      "assemblyVersion": "0.1.1.4",
      "dalamudApiLevel": 15,
      "author": "Johnneylee Jack Rollins",
      "punchline": "Model Context Protocol server for FINAL FANTASY XIV.",
      "description": "Exposes game state, game data and opt-in actions to MCP clients over loopback Streamable HTTP. Anything that changes your game is approved in game first. Optional Umbra toolbar widget.",
      "tags": [
        "mcp",
        "ai",
        "api",
        "utility"
      ],
      "icon": "https://spacegho.st/mods/ffxiv/plugins/icons/xivmcp.png",
      "images": [
        "https://spacegho.st/mods/ffxiv/plugins/icons/xivmcp-banner.png"
      ],
      "needs": "An MCP client on the same machine (Claude Code, Codex, Almanac).",
      "build": "dotnet build XivMcp.slnx -c Release",
      "umbraWidget": "Umbra.XivMcp",
      "released": true
    },
    {
      "internalName": "XivDesktop",
      "name": "XivDesktop",
      "listed": true,
      "repo": "Spaceghost/xivdesktop-dalamud",
      "assemblyVersion": "1.0.2.4",
      "dalamudApiLevel": 15,
      "author": "Johnneylee Jack Rollins",
      "punchline": "Launch Linux desktop apps into the game world.",
      "description": "An app launcher for FINAL FANTASY XIV running under Wine on Linux. Lists the host's freedesktop applications and opens them as world panels through Ghostty's remote windows. Optional Umbra toolbar widget.",
      "tags": [
        "launcher",
        "desktop",
        "linux",
        "utility"
      ],
      "icon": "https://spacegho.st/mods/ffxiv/plugins/icons/xivdesktop.png",
      "images": [
        "https://spacegho.st/mods/ffxiv/plugins/icons/xivdesktop-banner.png"
      ],
      "needs": "Ghostty and ghostty-agent, and a Linux host running the game under Wine.",
      "build": "dotnet build XivDesktop.slnx -c Release",
      "umbraWidget": null,
      "released": true
    },
    {
      "internalName": "XivArcade",
      "name": "XivArcade",
      "listed": true,
      "repo": "Spaceghost/xivarcade-dalamud",
      "assemblyVersion": "0.2.0.0",
      "dalamudApiLevel": 15,
      "author": "Johnneylee Jack Rollins",
      "punchline": "Your own classic games as game panels, with saves kept in step across your machines.",
      "description": "A library for the classic games you own, for FINAL FANTASY XIV running under Wine on Linux. /arcade lists the game files in folders you choose, starts them in RetroArch on the Linux host, and shows them as world panels through Ghostty when it is installed. Every save and save state lives in one folder that Syncthing copies between your machines. It downloads no games, BIOS files or artwork.",
      "tags": [
        "emulation",
        "retroarch",
        "linux",
        "saves",
        "utility"
      ],
      "icon": "https://spacegho.st/mods/ffxiv/plugins/icons/xivarcade.png",
      "images": [
        "https://spacegho.st/mods/ffxiv/plugins/icons/xivarcade-banner.png"
      ],
      "needs": "A Linux host running the game under Wine, RetroArch, and your own game files. Ghostty for panels and Syncthing for save sync are optional.",
      "build": "dotnet build XivArcade.slnx -c Release",
      "umbraWidget": null,
      "released": true
    },
    {
      "internalName": "XivWayfinder",
      "name": "XivWayfinder",
      "listed": true,
      "repo": "Spaceghost/xivwayfinder-dalamud",
      "assemblyVersion": "0.1.0.2",
      "dalamudApiLevel": 15,
      "author": "Johnneylee Jack Rollins",
      "punchline": "A softly glowing bead and the classic pointing glove show which way to go.",
      "description": "XivWayfinder points the way in FINAL FANTASY XIV: a softly pulsing bead floats a couple of yalms ahead of you in the direction to go, and the game's own white pointing glove points there too, sliding to the edge of the screen when the way is behind you. It follows, in order, a target you set with /wayfinder X Y or another plugin sets over IPC, your map flag, and your tracked quest's next step; in another zone it names the nearest aetheryte instead. With vnavmesh installed it points along the walkable path. It only points and never moves your character.",
      "tags": [
        "navigation",
        "quest",
        "flag",
        "overlay",
        "utility"
      ],
      "icon": "https://spacegho.st/mods/ffxiv/plugins/icons/xivwayfinder.png",
      "images": [
        "https://spacegho.st/mods/ffxiv/plugins/icons/xivwayfinder-banner.png"
      ],
      "needs": "Nothing beyond Dalamud (API 15), on Windows or Linux under Wine. vnavmesh is optional, for walkable paths.",
      "build": "tools/fetch-dalamud.sh, then tools/install-dev.sh (or dotnet build XivWayfinder.slnx -c Release)",
      "umbraWidget": null,
      "pending": "No release yet. Build it yourself in the meantime.",
      "released": true
    },
    {
      "internalName": "XivLantern",
      "name": "XivLantern",
      "listed": true,
      "repo": "Spaceghost/xivlantern-dalamud",
      "assemblyVersion": "0.1.0.3",
      "dalamudApiLevel": 15,
      "author": "Johnneylee Jack Rollins",
      "punchline": "Light a lantern for your friends: a friend list, 1:1 chat and channels of your own, peer to peer.",
      "description": "Friends light a lantern to say they are here. Add friends with a one-time invite, see whose lantern is lit, chat 1:1 and in channels you make, and hear from the mod's author in a channel only they can post to. Peer to peer over iroh: no Lantern server, and nothing from the game is ever sent — not your character's name, world or chat; your friends see the name you type. Off until you turn it on in settings, where it says exactly who can see what (including that relays see your IP address, and how to turn them off). Blocking, rate limits and no auto-accept.",
      "tags": [
        "social",
        "chat",
        "friends",
        "p2p",
        "privacy"
      ],
      "icon": "https://spacegho.st/mods/ffxiv/plugins/icons/xivlantern.png",
      "images": [
        "https://spacegho.st/mods/ffxiv/plugins/icons/xivlantern-banner.png"
      ],
      "needs": "Nothing beyond Dalamud (API 15); the network layer ships inside the plugin as lantern.dll. Friends running XivLantern too.",
      "build": "tools/build-native.sh (cargo and mingw-w64), then dotnet build src/XivLantern.Plugin/XivLantern.Plugin.csproj -c Release and tools/package.sh",
      "umbraWidget": null,
      "pending": "Only testing builds so far: turn on Get plugin testing builds in /xlsettings to see it.",
      "released": true
    },
    {
      "internalName": "XivPiano",
      "name": "XivPiano",
      "listed": true,
      "repo": "Spaceghost/xivpiano-dalamud",
      "assemblyVersion": "0.1.0.0",
      "dalamudApiLevel": 15,
      "author": "Johnneylee Jack Rollins",
      "punchline": "Your Pandora stations inside FFXIV: play, skip, thumbs, new stations.",
      "description": "XivPiano is a Pandora radio player inside FINAL FANTASY XIV, in the tradition of pianobar and Pithos. Sign in with your Pandora account and play your stations, skip, thumbs up or down, shelve a song you are tired of, bookmark it, ask why it was picked, and make new stations from an artist, a song or a genre. The song shows in the server info bar; /piano next and friends work from chat and macros, and other plugins can control it over IPC. It can mute the game's music while it plays and pause itself during cutscenes. Pandora is only available in the United States. Not affiliated with Pandora or Sirius XM.",
      "tags": [
        "music",
        "radio",
        "pandora",
        "audio",
        "utility"
      ],
      "icon": "https://spacegho.st/mods/ffxiv/plugins/icons/xivpiano.png",
      "images": [
        "https://spacegho.st/mods/ffxiv/plugins/icons/xivpiano-banner.png"
      ],
      "needs": "Dalamud (API 15), on Windows or Linux under Wine, and a Pandora account in the United States.",
      "build": "tools/fetch-dalamud.sh, then tools/install-dev.sh (or dotnet build XivPiano.slnx -c Release)",
      "umbraWidget": null,
      "pending": "No release yet. Build it yourself in the meantime.",
      "released": false
    }
  ]
};
